export type Transaction = {
  id: string;
  date: number; // epoch timestamp
  name: string;
  description: string;
  project: string;
  category: string;
  amount: number;
  type: "expense" | "income";
  status: "geplant" | "bezahlt" | "matched";
  donor?: string;
  transactionType?: "transaction" | "expected";
};

export const mockTransactions: Transaction[] = [
  {
    id: "1",
    date: new Date(2025, 9, 13).getTime(),
    name: "Amazon",
    description: "Sony Alpha VI, 18-150mm",
    project: "Crashkurs Steuern",
    category: "Equipment",
    amount: -30302.0,
    type: "expense",
    status: "geplant",
  },
  {
    id: "2",
    date: new Date(2025, 9, 13).getTime(),
    name: "Bertelsmann Stiftung",
    description: "Zuwendung für das Jahr 2025",
    project: "YFN 8.0, YFN 9.0",
    category: "Equipment",
    amount: 15000.0,
    type: "income",
    status: "bezahlt",
    donor: "BMW Stiftung",
  },
  {
    id: "3",
    date: new Date(2025, 9, 12).getTime(),
    name: "QiTech GmbH",
    description: "RE0514",
    project: "Crashkurs Steuern",
    category: "Freelancer",
    amount: -217.83,
    type: "expense",
    status: "bezahlt",
  },
  {
    id: "4",
    date: new Date(2025, 9, 10).getTime(),
    name: "DrinkForFood",
    description: "RF11",
    project: "YFN Schools",
    category: "Catering",
    amount: -240.0,
    type: "expense",
    status: "bezahlt",
  },
  {
    id: "5",
    date: new Date(2025, 9, 3).getTime(),
    name: "META",
    description: "Ads",
    project: "YFC",
    category: "Werbemittel",
    amount: -32.34,
    type: "expense",
    status: "bezahlt",
  },
  {
    id: "6",
    date: new Date(2025, 9, 15).getTime(),
    name: "Google Ads",
    description: "Marketing Campaign Q1",
    project: "YFN 9.0",
    category: "Werbemittel",
    amount: -450.0,
    type: "expense",
    status: "geplant",
  },
  {
    id: "7",
    date: new Date(2025, 9, 8).getTime(),
    name: "Telekom",
    description: "Internet & Phone",
    project: "YFC",
    category: "Office",
    amount: -89.99,
    type: "expense",
    status: "bezahlt",
  },
  {
    id: "8",
    date: new Date(2025, 9, 20).getTime(),
    name: "Freelancer Max",
    description: "Website Development",
    project: "YFN Schools",
    category: "Freelancer",
    amount: -1200.0,
    type: "expense",
    status: "geplant",
  },
  {
    id: "9",
    date: new Date(2025, 9, 5).getTime(),
    name: "Stadt München",
    description: "Förderung Bildungsprojekt",
    project: "YFN 8.0",
    category: "Grants",
    amount: 25000.0,
    type: "income",
    status: "bezahlt",
    donor: "Stadt München",
  },
  {
    id: "10",
    date: new Date(2025, 9, 18).getTime(),
    name: "Office Supplies GmbH",
    description: "Büromaterial Q1",
    project: "YFC",
    category: "Office",
    amount: -156.78,
    type: "expense",
    status: "geplant",
  },
  {
    id: "11",
    date: new Date(2025, 8, 15).getTime(),
    name: "Privatspende Schmidt",
    description: "Spende für Jugendarbeit",
    project: "YFN 9.0",
    category: "Donations",
    amount: 2000.0,
    type: "income",
    status: "bezahlt",
    donor: "Privatspende Schmidt",
  },
  {
    id: "12",
    date: new Date(2025, 9, 22).getTime(),
    name: "CVJM Bayern",
    description: "Förderung Q3",
    project: "YFN Schools",
    category: "Grants",
    amount: 4000.0,
    type: "income",
    status: "bezahlt",
    donor: "CVJM Bayern",
  },
  {
    id: "13",
    date: new Date(2025, 10, 1).getTime(),
    name: "Aktion Mensch",
    description: "Projektförderung Teil 1",
    project: "YFN 9.0",
    category: "Grants",
    amount: 12500.0,
    type: "income",
    status: "bezahlt",
    donor: "Aktion Mensch",
  },
  {
    id: "14",
    date: new Date(2025, 10, 15).getTime(),
    name: "Google.org",
    description: "Tech for Good Grant",
    project: "YFN 8.0",
    category: "Sponsoring",
    amount: 15000.0,
    type: "income",
    status: "bezahlt",
    donor: "Google.org",
  },
];
