export const CATEGORY_GROUPS = [
  {
    group: "Mitgliedsbeiträge & Gebühren",
    type: "income" as const,
    items: [
      {
        value: "membership-fees",
        label: "Mitgliedsbeiträge",
        description: "Regelmäßige Beiträge der Vereinsmitglieder",
        taxsphere: "non-profit" as const,
      },
      {
        value: "admission-fees",
        label: "Aufnahmegebühren",
        description: "Einmalige Gebühren bei Vereinseintritt",
        taxsphere: "non-profit" as const,
      },
      {
        value: "participation-fees",
        label: "Teilnahmegebühren",
        description: "Gebühren für Workshops, Kurse, Seminare",
        taxsphere: "purpose-operations" as const,
      },
    ],
  },
  {
    group: "Veranstaltungseinnahmen & Sponsoring",
    type: "income" as const,
    items: [
      {
        value: "ticket-sales",
        label: "Ticketverkäufe/Eintrittsgelder",
        description: "Einnahmen aus Ticketverkauf für Events",
        taxsphere: "purpose-operations" as const,
      },
      {
        value: "workshop-income",
        label: "Workshop-Einnahmen",
        description: "Erlöse aus kostenpflichtigen Workshops",
        taxsphere: "purpose-operations" as const,
      },
      {
        value: "catering-sales",
        label: "Catering-Verkäufe",
        description: "Verkauf von Speisen und Getränken bei Events",
        taxsphere: "purpose-operations" as const,
      },
      {
        value: "merchandising",
        label: "Merchandising",
        description: "Verkauf von Fanartikeln und Merchandise",
        taxsphere: "commercial-operations" as const,
      },
      {
        value: "sponsorship-cash",
        label: "Sponsoring (Geldleistung)",
        description: "Finanzielle Unterstützung durch Sponsoren",
        taxsphere: "commercial-operations" as const,
      },
      {
        value: "sponsorship-in-kind",
        label: "Sponsoring (Sachleistung)",
        description: "Material- und Dienstleistungssponsoring",
        taxsphere: "commercial-operations" as const,
      },
      {
        value: "advertising-income",
        label: "Werbeeinnahmen",
        description: "Einnahmen aus Werbeflächen und -anzeigen",
        taxsphere: "commercial-operations" as const,
      },
    ],
  },
  {
    group: "Spenden & Förderungen",
    type: "income" as const,
    items: [
      {
        value: "monetary-donations",
        label: "Geldspenden",
        description: "Finanzielle Zuwendungen ohne Gegenleistung",
        taxsphere: "non-profit" as const,
      },
      {
        value: "donated-goods",
        label: "Sachspenden",
        description: "Gespendete Gegenstände und Materialien",
        taxsphere: "non-profit" as const,
      },
      {
        value: "crowdfunding",
        label: "Crowdfunding",
        description: "Einnahmen aus Crowdfunding-Kampagnen",
        taxsphere: "non-profit" as const,
      },
      {
        value: "public-funding",
        label: "Öffentliche Förderung",
        description: "Zuschüsse von Bund, Land, Kommune",
        taxsphere: "non-profit" as const,
      },
      {
        value: "university-funding",
        label: "Hochschulförderung",
        description: "Förderung durch Studierendenparlament/AStA",
        taxsphere: "non-profit" as const,
      },
      {
        value: "foundation-funding",
        label: "Stiftungsförderung",
        description: "Zuwendungen von Stiftungen",
        taxsphere: "non-profit" as const,
      },
      {
        value: "association-subsidy",
        label: "Verbandszuschuss",
        description: "Zuschüsse von Dach- und Fachverbänden",
        taxsphere: "non-profit" as const,
      },
    ],
  },
  {
    group: "Vermögensverwaltung",
    type: "income" as const,
    items: [
      {
        value: "interest-income",
        label: "Zinseinnahmen",
        description: "Zinsen auf Sparguthaben und Anlagen",
        taxsphere: "asset-management" as const,
      },
      {
        value: "rental-income",
        label: "Mieteinnahmen",
        description: "Vermietung von Vereinsräumen oder -gegenständen",
        taxsphere: "asset-management" as const,
      },
      {
        value: "capital-gains",
        label: "Veräußerungsgewinne",
        description: "Erlöse aus Verkauf von Vermögensgegenständen",
        taxsphere: "asset-management" as const,
      },
      {
        value: "emergency-buffer",
        label: "Notfall-Puffer",
        description: "Reserve für unvorhergesehene Ausgaben",
        taxsphere: "non-profit" as const,
      },
    ],
  },
  {
    group: "Verpflegung",
    type: "expense" as const,
    items: [
      {
        value: "food-catering",
        label: "Essen/Catering",
        description: "Kosten für Speisen und Catering-Service",
        taxsphere: "purpose-operations" as const,
      },
      {
        value: "beverages-nonalcoholic",
        label: "Getränke (alkoholfrei)",
        description: "Wasser, Säfte, Softdrinks",
        taxsphere: "purpose-operations" as const,
      },
      {
        value: "beverages-alcoholic",
        label: "Getränke (alkoholisch)",
        description: "Bier, Wein, Spirituosen",
        taxsphere: "purpose-operations" as const,
      },
      {
        value: "helper-catering",
        label: "Helfer-Verpflegung",
        description: "Verpflegung für ehrenamtliche Helfer",
        taxsphere: "purpose-operations" as const,
      },
      {
        value: "speaker-catering",
        label: "Speaker-Catering",
        description: "Spezielle Verpflegung für Referenten",
        taxsphere: "purpose-operations" as const,
      },
    ],
  },
  {
    group: "Location & Infrastruktur",
    type: "expense" as const,
    items: [
      {
        value: "room-rental",
        label: "Raummiete",
        description: "Miete für Veranstaltungsräume",
        taxsphere: "purpose-operations" as const,
      },
      {
        value: "additional-costs",
        label: "Nebenkosten (Reinigung, Energie)",
        description: "Zusätzliche Kosten für Reinigung und Energie",
        taxsphere: "purpose-operations" as const,
      },
      {
        value: "deposit",
        label: "Kaution",
        description: "Sicherheitskaution für Location",
        taxsphere: "purpose-operations" as const,
      },
      {
        value: "technical-equipment",
        label: "Technik (Beamer, Mikrofone, Leinwand)",
        description: "Grundlegende Veranstaltungstechnik",
        taxsphere: "purpose-operations" as const,
      },
      {
        value: "lighting-sound",
        label: "Licht & Tontechnik",
        description: "Professionelle Licht- und Tontechnik",
        taxsphere: "purpose-operations" as const,
      },

      {
        value: "wlan-it-infrastructure",
        label: "WLAN/IT-Infrastruktur",
        description: "Internet und IT-Infrastruktur",
        taxsphere: "purpose-operations" as const,
      },
      {
        value: "gema-fees",
        label: "GEMA-Gebühren",
        description: "Gebühren für Musikrechte",
        taxsphere: "purpose-operations" as const,
      },
      {
        value: "decoration",
        label: "Dekoration",
        description: "Dekorationsmaterial",
        taxsphere: "purpose-operations" as const,
      },
    ],
  },
  {
    group: "Honorare & Personal",
    type: "expense" as const,
    items: [
      {
        value: "speaker-fees",
        label: "Speaker-Honorare",
        description: "Honorare für Referenten und Vortragende",
        taxsphere: "purpose-operations" as const,
      },
      {
        value: "moderator-fees",
        label: "Moderatoren-Honorare",
        description: "Honorare für Moderatoren",
        taxsphere: "purpose-operations" as const,
      },
      {
        value: "workshop-leader",
        label: "Workshop-Leiter",
        description: "Honorare für Workshop-Leiter",
        taxsphere: "purpose-operations" as const,
      },
      {
        value: "volunteer-allowance",
        label: "Ehrenamtspauschale",
        description: "Pauschale für ehrenamtliche Tätigkeiten (840€/Jahr)",
        taxsphere: "purpose-operations" as const,
      },
      {
        value: "course-instructor-allowance",
        label: "Übungsleiterpauschale",
        description: "Steuerfreie Übungsleiterpauschale (3.000€/Jahr)",
        taxsphere: "purpose-operations" as const,
      },
      {
        value: "minijobs",
        label: "Minijobs",
        description: "Kosten für geringfügige Beschäftigungen",
        taxsphere: "purpose-operations" as const,
      },
      {
        value: "student-assistant",
        label: "Studentische Hilfskraft/Werkstudent",
        description: "Vergütung für studentische Mitarbeiter",
        taxsphere: "purpose-operations" as const,
      },
      {
        value: "ksk-contributions",
        label: "KSK-Abgaben",
        description: "Künstlersozialkasse-Abgaben",
        taxsphere: "purpose-operations" as const,
      },
    ],
  },
  {
    group: "Reisekosten",
    type: "expense" as const,
    items: [
      {
        value: "train-tickets",
        label: "Bahntickets",
        description: "Zugfahrkarten für Anreise",
        taxsphere: "purpose-operations" as const,
      },
      {
        value: "flights",
        label: "Flüge",
        description: "Flugkosten für Anreise",
        taxsphere: "purpose-operations" as const,
      },
      {
        value: "hotel",
        label: "Hotel-Übernachtungen",
        description: "Übernachtungskosten",
        taxsphere: "purpose-operations" as const,
      },
      {
        value: "taxi-transfers",
        label: "Taxi/Transfers",
        description: "Lokale Transportkosten",
        taxsphere: "purpose-operations" as const,
      },
      {
        value: "mileage-allowance",
        label: "Kilometerpauschale",
        description: "Pauschale für PKW-Nutzung",
        taxsphere: "purpose-operations" as const,
      },
    ],
  },
  {
    group: "Verwaltung & IT",
    type: "expense" as const,
    items: [
      {
        value: "office-supplies",
        label: "Büromaterial",
        description: "Schreibwaren und Bürobedarf",
        taxsphere: "non-profit" as const,
      },
      {
        value: "postage-shipping",
        label: "Porto & Versand",
        description: "Versandkosten und Porto",
        taxsphere: "non-profit" as const,
      },
      {
        value: "bank-fees",
        label: "Bankgebühren",
        description: "Kontoführungs- und Transaktionsgebühren",
        taxsphere: "non-profit" as const,
      },
      {
        value: "tax-consulting",
        label: "Steuerberatung",
        description: "Honorare für Steuerberater",
        taxsphere: "non-profit" as const,
      },
      {
        value: "legal-advice",
        label: "Rechtsberatung",
        description: "Honorare für Rechtsberatung",
        taxsphere: "non-profit" as const,
      },
      {
        value: "insurance",
        label: "Versicherungen",
        description: "Verschiedene Versicherungen",
        taxsphere: "non-profit" as const,
      },
      {
        value: "domain-hosting",
        label: "Domain & Hosting",
        description: "Domain-Registrierung und Webhosting",
        taxsphere: "purpose-operations" as const,
      },
      {
        value: "equipment-inventory",
        label: "Ausstattung & Inventar",
        description: "Anschaffungen von Geräten und Material",
        taxsphere: "asset-management" as const,
      },
    ],
  },
];
