import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import { AppSidebar } from "./components/Sidebar/AppSidebar";
import { SidebarProvider, SidebarTrigger } from "./components/ui/sidebar";
import "./globals.css";
import { ConvexClientProvider } from "./provider/ConvexClientProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <SidebarProvider>
        <AppSidebar />
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <SidebarTrigger />
          {children}
          <ConvexClientProvider>{children}</ConvexClientProvider>
        </body>
      </SidebarProvider>
    </html>
  );
}
