import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import { AppSidebar } from "./components/Sidebar/AppSidebar";
import { SidebarProvider } from "./components/ui/sidebar";
import { DateRangeProvider } from "./contexts/DateRangeContext";
import "./globals.css";
import { ConvexClientProvider } from "./provider/ConvexClientProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning
      >
        <ConvexClientProvider>
          <DateRangeProvider>
            <SidebarProvider>
              <AppSidebar />
              {children}
            </SidebarProvider>
          </DateRangeProvider>
        </ConvexClientProvider>
      </body>
    </html>
  );
}
